### ISSUE TITLE
court und court_type sollten zusammenpassen

### ISSUE THREAD

**Issue by stefanw** [okfde/froide-legalaction#4]
Es ergeben sich manchmal solche unsinnigen Ansichten:

<img width="352" alt="Screenshot 2021-04-06 at 16 22 52" src="https://user-images.githubusercontent.com/78356/113735739-725fce00-96f4-11eb-8b05-ae103204190e.png">

Vielleicht weil die nächste Instanz in der Klage BVerfg ist? Oder ist das ein Fehler in der Eingabe? Ggf. muss `court_type` weg und aus der Gerichts-Behörde via classification inferiert werden.

**Comment by arnese** [comment]
Das ist mein Fehler in der Eingabe bzw. Unklarheit bei mir, ob ich dann beides ändern soll, wenn Eingangsklage VG war und das Ding inzwischen beim BVerfG: https://fragdenstaat.de/fds-admin/froide_legalaction/lawsuit/17/change/

**Comment by stefanw** [comment]
Die Klage braucht wohle eine Historie.
